#!/usr/bin/env bash
# Build the throwaway Factorio environment the integration tier runs in.
#
# The mod under test is mirrored as a directory of symlinks rather than one
# symlink to the repo root: the environment lives inside the repo, so linking
# the whole tree would make the mods directory contain itself.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
here="$root/test/integration"
env_dir="$here/env"
mods="$env_dir/mods"
write_data="$env_dir/write-data"

rm -rf "$mods"
mkdir -p "$mods" "$write_data"

# AUPC_FROM_ZIP runs the packaged mod instead of the working tree, which is the
# only way to find out whether packaging left something out. Everything else
# about the run is identical.
if [[ -n "${AUPC_FROM_ZIP:-}" ]]; then
    [[ -f "$AUPC_FROM_ZIP" ]] || { echo "no zip at $AUPC_FROM_ZIP" >&2; exit 2; }
    cp "$AUPC_FROM_ZIP" "$mods/"
    echo "mod under test: $(basename "$AUPC_FROM_ZIP")"
else
    mkdir -p "$mods/automatic-underground-pipe-connectors"
    # Mirror what the package ships rather than a hand-kept list. A hand-kept one
    # already went stale once: settings.lua and locale/ were missing here long
    # after the mod needed them, and the setting simply did not exist in game.
    # Unquoted glob skips dotfiles, so .git and .luacheckrc stay out on their own.
    for path in "$root"/*; do
        entry="$(basename "$path")"
        case "$entry" in
            test|*.zip) continue ;;
        esac
        ln -sfn "$path" "$mods/automatic-underground-pipe-connectors/$entry"
    done
    echo "mod under test: the working tree"
fi
# The substitution option cannot be flipped from inside the game: Factorio only
# lets the owning player or the owning mod change a setting, and the scenario is
# neither. So it is written here, before the game starts. rm -rf above already
# cleared any previous file, which is what leaves the default in place.
if [[ -n "${AUPC_SUBSTITUTE_QUALITY:-}" ]]; then
    factorio="${AUPC_FACTORIO:-/home/sparr/Games/Steam/steamapps/common/Factorio/bin/x64/factorio}"
    version="$("$factorio" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)"
    lua5.2 "$here/mod-settings.lua" "$mods/mod-settings.dat" \
        aupc-substitute-pipe-quality true ${version:+"$version"}
    echo "quality substitution: on"
else
    echo "quality substitution: off (the default)"
fi

ln -sfn "$here/aupc-tests" "$mods/aupc-tests"

# The scenario cannot read environment variables, so the mode it should run in is
# handed to it as a generated file it requires. Regenerated every run, never
# committed, and the scenario defaults to headless if it is missing.
cat > "$here/aupc-tests/scenarios/aupc/mode.lua" <<LUA
-- Generated by test/integration/setup.sh. Do not edit; do not commit.
return {
    walkthrough = ${AUPC_WALKTHROUGH:-false},
}
LUA

cat > "$mods/mod-list.json" <<'JSON'
{
  "mods": [
    { "name": "base", "enabled": true },
    { "name": "elevated-rails", "enabled": true },
    { "name": "quality", "enabled": true },
    { "name": "space-age", "enabled": true },
    { "name": "automatic-underground-pipe-connectors", "enabled": true },
    { "name": "aupc-tests", "enabled": true }
  ]
}
JSON

# Muting has to happen here: Factorio has no --disable-audio, and it rewrites
# this file on exit, so a run that turned the sound up leaves it up.
cat > "$env_dir/config.ini" <<INI
[path]
read-data=__PATH__system-read-data__
write-data=$write_data

[general]
locale=en

[sound]
master-volume=0

[graphics]
graphics-quality=medium
video-memory-usage=low
INI

echo "environment ready at $env_dir"
